### ISSUE TITLE
dfs `enterVertex` call sequence is inconsistent with CLR discovery time.

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [ekmett/graphs#5]
When I run the dfs algorithm on the graph:
`g = array (0, 3) [(0, [1,2]), (1, [3]), (2, [3]), (3, [])]`
The order of the calls to `enterVertex` is [0,1,2,3] on the other hand if they are ordered
according to the discovery times of CLR's algorithm it would be [0,1,3,2].
I'm not sure if you intended a different meaning for `exploreVertex` or if this is a bug.
This is using the hackage version 5.0.1.
@ekmett

**Comment by ekmett** [comment]
Honestly? It is probably a bug.

I more or less transcoded the algorithms from boost as a way to explore one way to implement algorithms in Haskell and haven't really touched this package very much since.

**Comment by jeffreyrosenbluth** [comment]
No worries, I'm trying to replace the algorithm with one that fixes both #4 and #5.
If it works I'll push it and we can see what you think.

**Comment by jeffreyrosenbluth** [comment]
fixed in fixDFS branch
